// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAFDTC1rJ18nIlwl9038QbZWXxlHrpNJU',
    appId: '1:752895085034:web:2e834e4ce9fecc3023ca93',
    messagingSenderId: '752895085034',
    projectId: 'flutter-chatting-bc583',
    authDomain: 'flutter-chatting-bc583.firebaseapp.com',
    storageBucket: 'flutter-chatting-bc583.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3XMCKKJkSwv8Fb6RCbr0Rf8AgmNTApI4',
    appId: '1:752895085034:android:84a7ef3e46f0636823ca93',
    messagingSenderId: '752895085034',
    projectId: 'flutter-chatting-bc583',
    storageBucket: 'flutter-chatting-bc583.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBm4rBWFAuAqlaOWENm28xCcyiG3iDbQ8',
    appId: '1:752895085034:ios:ec7de314fa1b403423ca93',
    messagingSenderId: '752895085034',
    projectId: 'flutter-chatting-bc583',
    storageBucket: 'flutter-chatting-bc583.firebasestorage.app',
    iosBundleId: 'com.example.chatting',
  );
}
